### ISSUE TITLE
UnhandledPromiseRejectionWarning on Promise error

### ISSUE THREAD

**Issue by israelmuca** [scopsy/await-to-js#28]
Hi!
First of all, thanks for your package, I'm refactoring my code and it's been handy to make it more clear.

But I have an issue, when the promise resolves, everything goes ok, but when the promise fails, I get an error:

>(node:52113) UnhandledPromiseRejectionWarning: TypeError: arr[Symbol.iterator] is not a function
    at _iterableToArrayLimit (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/@babel/runtime/helpers/iterableToArrayLimit.js:8:39)
    at _slicedToArray (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/@babel/runtime/helpers/slicedToArray.js:8:33)
    at _callee2$ (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/src/controllers/auth.controller.js:72:26)
    at tryCatch (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at propagateAslWrapper (/Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/async-listener/index.js:504:23)
    at /Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/async-listener/glue.js:188:31
    at /Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/async-listener/index.js:541:70
    at /Users/israelmuca/Software/Dev/GitHub/techcrm-backend/node_modules/async-listener/glue.js:188:31
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:52113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:52113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by israelmuca** [comment]
My bad, I had a **(silly)** error on my code.
